### ISSUE TITLE
Images not loading in gmail

### ISSUE THREAD

**Issue by Fizqen** [al3xsus/email-signature-generator#1]
Logo images ( twitter etc ) are being hidden in gmail when adding signature. Any idea why?

**Comment by al3xsus** [comment]
Hi.
There were a few hints I mentioned in the article:
  _a) no SVGs - gmail proxy block it and gmail generally don't support it;
  b) no base64 - gmail doesn't support it and don't forget about the global limit of 10000 symbols for web-based clients and 12000 for desktop ones (and base64 are usualy really long)
  c) don't forget to disable react-scripts\webpack function of converting small images to base64 utilizing the environment variable IMAGE_INLINE_SIZE_LIMIT_
Can any of those be helpful?

**Comment by Fizqen** [comment]
Maybe, I did however try your [generator](https://al3xsus.github.io/email-signature-generator/?fbclid=IwAR1toHN96inwjYMpjPHg--md4JqJB8s1yryrWHzH5BXYvxuQfgeRQd29IUE) and it still did not work.

**Comment by al3xsus** [comment]
I made a temporary fix, and now it works.
Later I'll refactor the project.
